stages:
  # - static_analysis
  - test

.common-rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

default:
  image: python:3.12
  before_script:
    - apt-get update && apt-get install -y git
    - pip install pipenv
    - pipenv install

# formatting:
#   stage: static_analysis
#   extends: .common-rules
#   script:
#     - pipenv run black --check .
# types:
#   stage: static_analysis
#   extends: .common-rules
#   script:
#     - pipenv run mypy src/*
# lint:
#   stage: static_analysis
#   extends: .common-rules
#   script:
#     - pipenv run pylint src/
test:
  stage: test
  extends: .common-rules
  script:
    - pipenv run pytest -s test
# coverage:
#   stage: test
#   extends: .common-rules
#   script:
#     - pipenv run coverage run -m pytest
#     - pipenv run coverage report --fail-under=80
#   artifacts:
#     reports:
#       coverage_report:
#         coverage_format: cobertura
#         path: coverage.xml
#     paths:
#       - htmlcov/
#   after_script:
#     - pipenv run coverage xml
#     - pipenv run coverage html
#   coverage: '/TOTAL.*\s+(\d+)%/'