stages:
  - run

default:
  image: python:3.12
  before_script:
    - apt-get update && apt-get install -y git
    - pip install pipenv
    - pipenv install

run:
  stage: run
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - pipenv run pytest -s test